### ISSUE TITLE
fetch is note a function

### ISSUE THREAD

**Issue by ash-hashtag** [planetscale/database-js-starter#1]
*not
at postJSON (node_modules/@planetscale/database/dist/index.js:80:28)
at Connection.execute (node_modules/@planetscale/database/dist/index.js:48:29)

**Comment by fooforge** [comment]
Apologies for the slow response! Looks like you're on a `node` version < 18. From Node.js 18 on, the `fetch` function is in the global scope. Versions prior to 18 need to use another fetch implementation, like `undici`.

```bash
$ node --version
v18.7.0
$ node -e 'console.log(fetch)'
[AsyncFunction: fetch]
```

Closing this, but feel free to reopen if you do, in fact, see any issues with Node.js 18.
